esphome:
  name: mpu6050-sensor-node

esp8266:
  board: nodemcuv2

# Enable logging
logger:

ota:
  password: ""

wifi:
  ssid: "Velte Vunk"
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mpu6050-Sensor-Node"
    password: "gKTXqCNsiJZi"

i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

mqtt:
  broker: 192.168.178.53
  username: test
  password: test
  on_message:
     - topic: actions/stop
       then:
       - switch.turn_off: relay_switch
     - topic: actions/start
       then:
       - switch.turn_off: relay_switch       
captive_portal:

switch:
  - platform: gpio
    id: relay_switch
    pin: D5
    name: "Relay"
sensor:
  - platform: mpu6050
    address: 0x68
    accel_x:
      name: "MPU6050 Accel X"
    accel_y:
      name: "MPU6050 Accel Y"
    accel_z:
      name: "MPU6050 Accel z"
    gyro_x:
      name: "MPU6050 Gyro X"
    gyro_y:
      name: "MPU6050 Gyro Y"
    gyro_z:
      name: "MPU6050 Gyro z"
    temperature:
      name: "MPU6050 Temperature"