esphome:
  name: sensor

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XzNABx7gLozlLYSFfbXrvlcM8T9hgPKVkGB+8X0JuTc="

ota:
  password: "208b96462da31a869433453d650b9b30"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Fallback Hotspot"
    password: "7oiqK5v4w2ec"

captive_portal:
    