esphome:
  name: test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Z5bP9pgWyoBUbx41mmVPSSyS8elhwOhgZTsCQn9ZQRg="

ota:
  password: "e5ac499f73a8fe5dcaf6206584aff7fc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "njeXeqKfYhgM"

captive_portal:
    